from __future__ import annotations

import random
from dataclasses import dataclass, field
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

import requests
import urllib3

from xsscane.core.config import ScanConfig
from xsscane.core.http_client import _USER_AGENTS

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Statuses a WAF typically returns when it blocks an attack-looking request.
_BLOCK_STATUSES = {403, 406, 419, 429, 444, 406, 501, 502, 503}
_BLOCK_PHRASES = (
    "access denied", "request blocked", "request rejected", "forbidden",
    "not acceptable", "has been blocked", "blocked by", "security policy",
    "the requested url was rejected", "unusual traffic", "are you a robot",
)

# Header / cookie / server / body fingerprints for common WAFs and CDNs. Matching
# is substring-based and case-insensitive — the same approach wafw00f uses.
_SIGNATURES = [
    {"name": "Cloudflare", "server": ["cloudflare"],
     "headers": ["cf-ray", "cf-cache-status", "cf-mitigated"],
     "cookies": ["__cfduid", "cf_clearance", "__cf_bm"],
     "body": ["attention required! | cloudflare", "cloudflare ray id", "error 1020"]},
    {"name": "Akamai", "server": ["akamaighost"],
     "headers": ["x-akamai-transformed", "akamai-grn"],
     "cookies": ["ak_bmsc", "_abck", "bm_sz"],
     "body": ["reference #", "akamai"]},
    # Rely on AWS-specific headers/cookies, not a generic "request blocked" page
    # (that phrase is handled by the block-page heuristic, not attributed to AWS).
    {"name": "AWS WAF", "server": ["awselb"],
     "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-trace-id"],
     "cookies": ["aws-waf-token"]},
    {"name": "Imperva Incapsula",
     "headers": ["x-iinfo", "x-cdn"],
     "cookies": ["incap_ses", "visid_incap", "nlbi_"],
     "body": ["incapsula incident id", "_incapsula_resource", "powered by incapsula"]},
    {"name": "F5 BIG-IP ASM",
     "cookies": ["bigipserver", "f5_", "ts01"],
     "body": ["the requested url was rejected", "please consult with your administrator"]},
    {"name": "Sucuri CloudProxy", "server": ["sucuri/cloudproxy"],
     "headers": ["x-sucuri-id", "x-sucuri-cache"],
     "body": ["sucuri website firewall", "access denied - sucuri"]},
    {"name": "ModSecurity", "server": ["mod_security", "modsecurity"],
     "body": ["mod_security", "this error was generated by mod_security", "noyb"]},
    {"name": "Wordfence",
     "cookies": ["wfvt_", "wordfence_verifiedhuman"],
     "body": ["generated by wordfence", "your access to this site has been limited"]},
    {"name": "Barracuda",
     "cookies": ["barra_counter_session"],
     "body": ["barracuda", "you have been blocked"]},
    {"name": "Fortinet FortiWeb",
     "cookies": ["fortiwafsid"],
     "body": ["fortigate", ".fgd_icon", "fortiweb"]},
    {"name": "DDoS-Guard", "server": ["ddos-guard"], "body": ["ddos-guard"]},
    {"name": "StackPath", "server": ["stackpath"], "body": ["stackpath"]},
    {"name": "Reblaze", "cookies": ["rbzid", "rbzsessionid"], "body": ["reblaze"]},
]

# A loud, obviously-malicious value designed to trip signature-based WAF rules.
_ATTACK_VALUE = "<script>alert(1)</script>' OR 1=1-- -../../etc/passwd"


@dataclass
class WafResult:
    detected: bool = False
    name: str | None = None
    confidence: float = 0.0
    blocking: bool = False
    indicators: list[str] = field(default_factory=list)


class WafFingerprinter:
    """Detects a WAF/CDN in front of the target by comparing a benign request with
    an attack-looking one and matching headers, cookies and block pages against
    known fingerprints. Read-only reconnaissance — two requests, no exploitation."""

    def __init__(self, config: ScanConfig):
        self.config = config

    def fingerprint(self) -> WafResult:
        baseline = self._fetch(self.config.url)
        if baseline is None:
            return WafResult(indicators=["target unreachable"])
        attack = self._fetch(self._attack_url(self.config.url))
        return self._analyze(baseline, attack)

    # -- transport ------------------------------------------------------------

    def _fetch(self, url: str) -> dict | None:
        headers = {"User-Agent": random.choice(_USER_AGENTS),
                   "Accept": "text/html,application/xhtml+xml,*/*;q=0.8"}
        proxies = {"http": self.config.proxy, "https": self.config.proxy} if self.config.proxy else None
        try:
            response = requests.get(
                url, headers=headers, proxies=proxies, timeout=self.config.timeout,
                verify=self.config.verify_tls, allow_redirects=True,
            )
        except requests.RequestException:
            return None
        return {
            "status": response.status_code,
            "header_keys": {k.lower() for k in response.headers},
            "server": response.headers.get("Server", "").lower(),
            "cookies": {c.name.lower() for c in response.cookies},
            "body": (response.text or "")[:8000].lower(),
        }

    @staticmethod
    def _attack_url(url: str) -> str:
        parsed = urlparse(url)
        params = dict(parse_qsl(parsed.query))
        params["wafprobe"] = _ATTACK_VALUE
        return urlunparse(parsed._replace(query=urlencode(params)))

    # -- analysis -------------------------------------------------------------

    def _analyze(self, baseline: dict, attack: dict | None) -> WafResult:
        responses = [baseline] + ([attack] if attack else [])
        header_keys = set().union(*(r["header_keys"] for r in responses))
        cookies = set().union(*(r["cookies"] for r in responses))
        server = " ".join(r["server"] for r in responses)
        body = " ".join(r["body"] for r in responses)

        blocking = bool(
            attack
            and baseline["status"] < 400
            and (attack["status"] in _BLOCK_STATUSES
                 or any(phrase in attack["body"] for phrase in _BLOCK_PHRASES))
        )

        best_name, best_indicators = None, []
        for sig in _SIGNATURES:
            indicators = []
            for header in sig.get("headers", []):
                if header in header_keys:
                    indicators.append(f"header:{header}")
            for cookie in sig.get("cookies", []):
                if any(cookie in name for name in cookies):
                    indicators.append(f"cookie:{cookie}")
            for token in sig.get("server", []):
                if token in server:
                    indicators.append(f"server:{token}")
            for token in sig.get("body", []):
                if token in body:
                    indicators.append(f"body:{token[:28]}")
            if len(indicators) > len(best_indicators):
                best_name, best_indicators = sig["name"], indicators

        if best_name:
            confidence = min(0.6 + 0.15 * len(best_indicators) + (0.15 if blocking else 0), 0.99)
            if blocking:
                best_indicators = best_indicators + ["blocking response"]
            return WafResult(True, best_name, round(confidence, 2), blocking, best_indicators)
        if blocking:
            return WafResult(True, "Generic / unknown WAF", 0.5, True, ["blocking response"])
        return WafResult(False, None, 0.0, False, [])
